[project]
name = "ppa-analysis"
version = "0.1.0"
description = "A tool to help prospective PPA buyers understand different types of PPA contracts and their potential outcomes, both financially and environmentally."
authors = [
    { name = "elkallmier", email = "e.kallmier@unsw.edu.au" },
    { name = "nick-gorman", email = "n.gorman305@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "holidays==0.48",
    "ipython==8.24.0",
    "ipywidgets==8.1.2",
    "matplotlib==3.8.4",
    "mip==1.16rc0",
    "nemed==0.3.2",
    "nemosis==3.7.0",
    "numpy==1.24.3",
    "pandas==1.5.3",
    "plotly==5.14.1",
    "python-dateutil==2.8.2",
    "seaborn==0.13.2",
]

[dependency-groups]
dev = [
    "jupyterlab==4.2.0",
    "notebook==7.2.0",
    "qtconsole==5.5.2",
]
